package com.xiaoyi.orderpayment.dao;

import com.xiaoyi.orderpayment.model.AuthInfo;
import com.xiaoyi.orderpayment.model.AuthInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_info
     *
     * @mbggenerated Fri Jan 22 18:29:17 CST 2016
     */
    int countByExample(AuthInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_info
     *
     * @mbggenerated Fri Jan 22 18:29:17 CST 2016
     */
    int deleteByExample(AuthInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_info
     *
     * @mbggenerated Fri Jan 22 18:29:17 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_info
     *
     * @mbggenerated Fri Jan 22 18:29:17 CST 2016
     */
    int insert(AuthInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_info
     *
     * @mbggenerated Fri Jan 22 18:29:17 CST 2016
     */
    int insertSelective(AuthInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_info
     *
     * @mbggenerated Fri Jan 22 18:29:17 CST 2016
     */
    List<AuthInfo> selectByExample(AuthInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_info
     *
     * @mbggenerated Fri Jan 22 18:29:17 CST 2016
     */
    AuthInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_info
     *
     * @mbggenerated Fri Jan 22 18:29:17 CST 2016
     */
    int updateByExampleSelective(@Param("record") AuthInfo record, @Param("example") AuthInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_info
     *
     * @mbggenerated Fri Jan 22 18:29:17 CST 2016
     */
    int updateByExample(@Param("record") AuthInfo record, @Param("example") AuthInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_info
     *
     * @mbggenerated Fri Jan 22 18:29:17 CST 2016
     */
    int updateByPrimaryKeySelective(AuthInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_info
     *
     * @mbggenerated Fri Jan 22 18:29:17 CST 2016
     */
    int updateByPrimaryKey(AuthInfo record);
}