package com.xiaoyi.orderpayment.dao;

import com.xiaoyi.orderpayment.model.BraintreePlanInfo;
import com.xiaoyi.orderpayment.model.BraintreePlanInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BraintreePlanInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_braintree_plans_info
     *
     * @mbggenerated Wed May 25 16:32:11 CST 2016
     */
    int countByExample(BraintreePlanInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_braintree_plans_info
     *
     * @mbggenerated Wed May 25 16:32:11 CST 2016
     */
    int deleteByExample(BraintreePlanInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_braintree_plans_info
     *
     * @mbggenerated Wed May 25 16:32:11 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_braintree_plans_info
     *
     * @mbggenerated Wed May 25 16:32:11 CST 2016
     */
    int insert(BraintreePlanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_braintree_plans_info
     *
     * @mbggenerated Wed May 25 16:32:11 CST 2016
     */
    int insertSelective(BraintreePlanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_braintree_plans_info
     *
     * @mbggenerated Wed May 25 16:32:11 CST 2016
     */
    List<BraintreePlanInfo> selectByExample(BraintreePlanInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_braintree_plans_info
     *
     * @mbggenerated Wed May 25 16:32:11 CST 2016
     */
    BraintreePlanInfo selectByPrimaryKey(Long id);
    
    BraintreePlanInfo selectBraintreePlanBySkuAndServicetime(Integer sku, Integer servicetime);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_braintree_plans_info
     *
     * @mbggenerated Wed May 25 16:32:11 CST 2016
     */
    int updateByExampleSelective(@Param("record") BraintreePlanInfo record, @Param("example") BraintreePlanInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_braintree_plans_info
     *
     * @mbggenerated Wed May 25 16:32:11 CST 2016
     */
    int updateByExample(@Param("record") BraintreePlanInfo record, @Param("example") BraintreePlanInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_braintree_plans_info
     *
     * @mbggenerated Wed May 25 16:32:11 CST 2016
     */
    int updateByPrimaryKeySelective(BraintreePlanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_braintree_plans_info
     *
     * @mbggenerated Wed May 25 16:32:11 CST 2016
     */
    int updateByPrimaryKey(BraintreePlanInfo record);
    
}