package com.xiaoyi.orderpayment.dao;

import com.xiaoyi.orderpayment.model.ProductInfo;
import com.xiaoyi.orderpayment.model.ProductInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_info
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    int countByExample(ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_info
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    int insert(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_info
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    int insertSelective(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_info
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    List<ProductInfo> selectByExampleWithBLOBs(ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_info
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    List<ProductInfo> selectByExample(ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_info
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    ProductInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_info
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") ProductInfo record, @Param("example") ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_info
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") ProductInfo record, @Param("example") ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_info
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    int updateByExample(@Param("record") ProductInfo record, @Param("example") ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_info
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    int updateByPrimaryKeySelective(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_info
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_info
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    int updateByPrimaryKey(ProductInfo record);
}