package com.xiaoyi.orderpayment.dao;

import com.xiaoyi.orderpayment.model.RechargeCardInfo;
import com.xiaoyi.orderpayment.model.RechargeCardInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RechargeCardInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rechargecard_info
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    int countByExample(RechargeCardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rechargecard_info
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    int deleteByExample(RechargeCardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rechargecard_info
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rechargecard_info
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    int insert(RechargeCardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rechargecard_info
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    int insertSelective(RechargeCardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rechargecard_info
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    List<RechargeCardInfo> selectByExample(RechargeCardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rechargecard_info
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    RechargeCardInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rechargecard_info
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    int updateByExampleSelective(@Param("record") RechargeCardInfo record, @Param("example") RechargeCardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rechargecard_info
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    int updateByExample(@Param("record") RechargeCardInfo record, @Param("example") RechargeCardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rechargecard_info
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    int updateByPrimaryKeySelective(RechargeCardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rechargecard_info
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    int updateByPrimaryKey(RechargeCardInfo record);
    
    int updateUsedStatusByPW(RechargeCardInfo record);
    
    long selectForRecordwithMaxId();
}