package com.xiaoyi.orderpayment.model;

public class AppInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info.id
     *
     * @mbggenerated Wed Nov 08 16:31:08 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info.app_id
     *
     * @mbggenerated Wed Nov 08 16:31:08 CST 2017
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info.app_key
     *
     * @mbggenerated Wed Nov 08 16:31:08 CST 2017
     */
    private String appKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info.callback_url
     *
     * @mbggenerated Wed Nov 08 16:31:08 CST 2017
     */
    private String callbackUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info.id
     *
     * @return the value of tb_app_info.id
     *
     * @mbggenerated Wed Nov 08 16:31:08 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info.id
     *
     * @param id the value for tb_app_info.id
     *
     * @mbggenerated Wed Nov 08 16:31:08 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info.app_id
     *
     * @return the value of tb_app_info.app_id
     *
     * @mbggenerated Wed Nov 08 16:31:08 CST 2017
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info.app_id
     *
     * @param appId the value for tb_app_info.app_id
     *
     * @mbggenerated Wed Nov 08 16:31:08 CST 2017
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info.app_key
     *
     * @return the value of tb_app_info.app_key
     *
     * @mbggenerated Wed Nov 08 16:31:08 CST 2017
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info.app_key
     *
     * @param appKey the value for tb_app_info.app_key
     *
     * @mbggenerated Wed Nov 08 16:31:08 CST 2017
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey == null ? null : appKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info.callback_url
     *
     * @return the value of tb_app_info.callback_url
     *
     * @mbggenerated Wed Nov 08 16:31:08 CST 2017
     */
    public String getCallbackUrl() {
        return callbackUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info.callback_url
     *
     * @param callbackUrl the value for tb_app_info.callback_url
     *
     * @mbggenerated Wed Nov 08 16:31:08 CST 2017
     */
    public void setCallbackUrl(String callbackUrl) {
        this.callbackUrl = callbackUrl == null ? null : callbackUrl.trim();
    }
}