package com.xiaoyi.orderpayment.model;

public class AuthInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_auth_info.id
     *
     * @mbggenerated Fri Jan 22 18:29:17 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_auth_info.app_id
     *
     * @mbggenerated Fri Jan 22 18:29:17 CST 2016
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_auth_info.app_key
     *
     * @mbggenerated Fri Jan 22 18:29:17 CST 2016
     */
    private String appKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_auth_info.id
     *
     * @return the value of tb_auth_info.id
     *
     * @mbggenerated Fri Jan 22 18:29:17 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_auth_info.id
     *
     * @param id the value for tb_auth_info.id
     *
     * @mbggenerated Fri Jan 22 18:29:17 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_auth_info.app_id
     *
     * @return the value of tb_auth_info.app_id
     *
     * @mbggenerated Fri Jan 22 18:29:17 CST 2016
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_auth_info.app_id
     *
     * @param appId the value for tb_auth_info.app_id
     *
     * @mbggenerated Fri Jan 22 18:29:17 CST 2016
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_auth_info.app_key
     *
     * @return the value of tb_auth_info.app_key
     *
     * @mbggenerated Fri Jan 22 18:29:17 CST 2016
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_auth_info.app_key
     *
     * @param appKey the value for tb_auth_info.app_key
     *
     * @mbggenerated Fri Jan 22 18:29:17 CST 2016
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey == null ? null : appKey.trim();
    }
}