package com.xiaoyi.orderpayment.model;

public class BraintreePlanInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_braintree_plans_info.id
     *
     * @mbggenerated Wed May 25 16:32:11 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_braintree_plans_info.plan_id
     *
     * @mbggenerated Wed May 25 16:32:11 CST 2016
     */
    private String planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_braintree_plans_info.sku
     *
     * @mbggenerated Wed May 25 16:32:11 CST 2016
     */
    private Integer sku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_braintree_plans_info.servicetime
     *
     * @mbggenerated Wed May 25 16:32:11 CST 2016
     */
    private Integer servicetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_braintree_plans_info.id
     *
     * @return the value of tb_braintree_plans_info.id
     *
     * @mbggenerated Wed May 25 16:32:11 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_braintree_plans_info.id
     *
     * @param id the value for tb_braintree_plans_info.id
     *
     * @mbggenerated Wed May 25 16:32:11 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_braintree_plans_info.plan_id
     *
     * @return the value of tb_braintree_plans_info.plan_id
     *
     * @mbggenerated Wed May 25 16:32:11 CST 2016
     */
    public String getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_braintree_plans_info.plan_id
     *
     * @param planId the value for tb_braintree_plans_info.plan_id
     *
     * @mbggenerated Wed May 25 16:32:11 CST 2016
     */
    public void setPlanId(String planId) {
        this.planId = planId == null ? null : planId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_braintree_plans_info.sku
     *
     * @return the value of tb_braintree_plans_info.sku
     *
     * @mbggenerated Wed May 25 16:32:11 CST 2016
     */
    public Integer getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_braintree_plans_info.sku
     *
     * @param sku the value for tb_braintree_plans_info.sku
     *
     * @mbggenerated Wed May 25 16:32:11 CST 2016
     */
    public void setSku(Integer sku) {
        this.sku = sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_braintree_plans_info.servicetime
     *
     * @return the value of tb_braintree_plans_info.servicetime
     *
     * @mbggenerated Wed May 25 16:32:11 CST 2016
     */
    public Integer getServicetime() {
        return servicetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_braintree_plans_info.servicetime
     *
     * @param servicetime the value for tb_braintree_plans_info.servicetime
     *
     * @mbggenerated Wed May 25 16:32:11 CST 2016
     */
    public void setServicetime(Integer servicetime) {
        this.servicetime = servicetime;
    }
}