package com.xiaoyi.orderpayment.model;

import java.util.Date;

public class OrderInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.id
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.order_code
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.customer_id
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.product_id
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.order_status
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.client_channel
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    private Integer clientChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.product_num
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    private Integer productNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.final_price
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    private Integer finalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.order_type
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    private Integer orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.last_modified
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    private Date lastModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.payment_type
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    private Integer paymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.date_finished
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    private Date dateFinished;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.date_paid
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    private Date datePaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.date_purchased
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    private Date datePurchased;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.original_price
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    private Integer originalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.order_currency
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    private String orderCurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.payment_code
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    private String paymentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.sku_id
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    private Long skuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.id
     *
     * @return the value of tb_order_info.id
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.id
     *
     * @param id the value for tb_order_info.id
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.order_code
     *
     * @return the value of tb_order_info.order_code
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.order_code
     *
     * @param orderCode the value for tb_order_info.order_code
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.customer_id
     *
     * @return the value of tb_order_info.customer_id
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.customer_id
     *
     * @param customerId the value for tb_order_info.customer_id
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.product_id
     *
     * @return the value of tb_order_info.product_id
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.product_id
     *
     * @param productId the value for tb_order_info.product_id
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.order_status
     *
     * @return the value of tb_order_info.order_status
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.order_status
     *
     * @param orderStatus the value for tb_order_info.order_status
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.client_channel
     *
     * @return the value of tb_order_info.client_channel
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public Integer getClientChannel() {
        return clientChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.client_channel
     *
     * @param clientChannel the value for tb_order_info.client_channel
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public void setClientChannel(Integer clientChannel) {
        this.clientChannel = clientChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.product_num
     *
     * @return the value of tb_order_info.product_num
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public Integer getProductNum() {
        return productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.product_num
     *
     * @param productNum the value for tb_order_info.product_num
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public void setProductNum(Integer productNum) {
        this.productNum = productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.final_price
     *
     * @return the value of tb_order_info.final_price
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public Integer getFinalPrice() {
        return finalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.final_price
     *
     * @param finalPrice the value for tb_order_info.final_price
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public void setFinalPrice(Integer finalPrice) {
        this.finalPrice = finalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.order_type
     *
     * @return the value of tb_order_info.order_type
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.order_type
     *
     * @param orderType the value for tb_order_info.order_type
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.last_modified
     *
     * @return the value of tb_order_info.last_modified
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public Date getLastModified() {
        return lastModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.last_modified
     *
     * @param lastModified the value for tb_order_info.last_modified
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public void setLastModified(Date lastModified) {
        this.lastModified = lastModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.payment_type
     *
     * @return the value of tb_order_info.payment_type
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public Integer getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.payment_type
     *
     * @param paymentType the value for tb_order_info.payment_type
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public void setPaymentType(Integer paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.date_finished
     *
     * @return the value of tb_order_info.date_finished
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public Date getDateFinished() {
        return dateFinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.date_finished
     *
     * @param dateFinished the value for tb_order_info.date_finished
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public void setDateFinished(Date dateFinished) {
        this.dateFinished = dateFinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.date_paid
     *
     * @return the value of tb_order_info.date_paid
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public Date getDatePaid() {
        return datePaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.date_paid
     *
     * @param datePaid the value for tb_order_info.date_paid
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public void setDatePaid(Date datePaid) {
        this.datePaid = datePaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.date_purchased
     *
     * @return the value of tb_order_info.date_purchased
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public Date getDatePurchased() {
        return datePurchased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.date_purchased
     *
     * @param datePurchased the value for tb_order_info.date_purchased
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public void setDatePurchased(Date datePurchased) {
        this.datePurchased = datePurchased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.original_price
     *
     * @return the value of tb_order_info.original_price
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public Integer getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.original_price
     *
     * @param originalPrice the value for tb_order_info.original_price
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public void setOriginalPrice(Integer originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.order_currency
     *
     * @return the value of tb_order_info.order_currency
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public String getOrderCurrency() {
        return orderCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.order_currency
     *
     * @param orderCurrency the value for tb_order_info.order_currency
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public void setOrderCurrency(String orderCurrency) {
        this.orderCurrency = orderCurrency == null ? null : orderCurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.payment_code
     *
     * @return the value of tb_order_info.payment_code
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public String getPaymentCode() {
        return paymentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.payment_code
     *
     * @param paymentCode the value for tb_order_info.payment_code
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public void setPaymentCode(String paymentCode) {
        this.paymentCode = paymentCode == null ? null : paymentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.sku_id
     *
     * @return the value of tb_order_info.sku_id
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.sku_id
     *
     * @param skuId the value for tb_order_info.sku_id
     *
     * @mbggenerated Thu May 10 14:47:14 CST 2018
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }
}