package com.xiaoyi.orderpayment.model;

import java.util.Date;

public class ProductInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_info.id
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_info.product_name
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_info.product_price
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    private Integer productPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_info.product_type
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    private Integer productType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_info.product_channel
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    private Integer productChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_info.product_availible
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    private Integer productAvailible;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_info.product_sku
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    private Long productSku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_info.date_modified
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    private Date dateModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_info.date_created
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    private Date dateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_info.currency
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_info.iap_identifier
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    private String iapIdentifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_info.product_img
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    private String productImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_info.product_description
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    private String productDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_info.id
     *
     * @return the value of tb_product_info.id
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_info.id
     *
     * @param id the value for tb_product_info.id
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_info.product_name
     *
     * @return the value of tb_product_info.product_name
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_info.product_name
     *
     * @param productName the value for tb_product_info.product_name
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_info.product_price
     *
     * @return the value of tb_product_info.product_price
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    public Integer getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_info.product_price
     *
     * @param productPrice the value for tb_product_info.product_price
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    public void setProductPrice(Integer productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_info.product_type
     *
     * @return the value of tb_product_info.product_type
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    public Integer getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_info.product_type
     *
     * @param productType the value for tb_product_info.product_type
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    public void setProductType(Integer productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_info.product_channel
     *
     * @return the value of tb_product_info.product_channel
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    public Integer getProductChannel() {
        return productChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_info.product_channel
     *
     * @param productChannel the value for tb_product_info.product_channel
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    public void setProductChannel(Integer productChannel) {
        this.productChannel = productChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_info.product_availible
     *
     * @return the value of tb_product_info.product_availible
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    public Integer getProductAvailible() {
        return productAvailible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_info.product_availible
     *
     * @param productAvailible the value for tb_product_info.product_availible
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    public void setProductAvailible(Integer productAvailible) {
        this.productAvailible = productAvailible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_info.product_sku
     *
     * @return the value of tb_product_info.product_sku
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    public Long getProductSku() {
        return productSku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_info.product_sku
     *
     * @param productSku the value for tb_product_info.product_sku
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    public void setProductSku(Long productSku) {
        this.productSku = productSku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_info.date_modified
     *
     * @return the value of tb_product_info.date_modified
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    public Date getDateModified() {
        return dateModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_info.date_modified
     *
     * @param dateModified the value for tb_product_info.date_modified
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_info.date_created
     *
     * @return the value of tb_product_info.date_created
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_info.date_created
     *
     * @param dateCreated the value for tb_product_info.date_created
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_info.currency
     *
     * @return the value of tb_product_info.currency
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_info.currency
     *
     * @param currency the value for tb_product_info.currency
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_info.iap_identifier
     *
     * @return the value of tb_product_info.iap_identifier
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    public String getIapIdentifier() {
        return iapIdentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_info.iap_identifier
     *
     * @param iapIdentifier the value for tb_product_info.iap_identifier
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    public void setIapIdentifier(String iapIdentifier) {
        this.iapIdentifier = iapIdentifier == null ? null : iapIdentifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_info.product_img
     *
     * @return the value of tb_product_info.product_img
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    public String getProductImg() {
        return productImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_info.product_img
     *
     * @param productImg the value for tb_product_info.product_img
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    public void setProductImg(String productImg) {
        this.productImg = productImg == null ? null : productImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_info.product_description
     *
     * @return the value of tb_product_info.product_description
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    public String getProductDescription() {
        return productDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_info.product_description
     *
     * @param productDescription the value for tb_product_info.product_description
     *
     * @mbggenerated Wed Nov 08 15:19:43 CST 2017
     */
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription == null ? null : productDescription.trim();
    }
}