package com.xiaoyi.orderpayment.model;

import java.util.Date;

public class RechargeCardInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rechargecard_info.id
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rechargecard_info.sn
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    private String sn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rechargecard_info.pw
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    private String pw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rechargecard_info.used
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    private Integer used;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rechargecard_info.sku
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    private Long sku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rechargecard_info.price
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rechargecard_info.currency
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rechargecard_info.used_time
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    private Date usedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rechargecard_info.created_by
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    private Integer createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rechargecard_info.expired_time
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    private Date expiredTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rechargecard_info.created_time
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    private Date createdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rechargecard_info.id
     *
     * @return the value of tb_rechargecard_info.id
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rechargecard_info.id
     *
     * @param id the value for tb_rechargecard_info.id
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rechargecard_info.sn
     *
     * @return the value of tb_rechargecard_info.sn
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rechargecard_info.sn
     *
     * @param sn the value for tb_rechargecard_info.sn
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    public void setSn(String sn) {
        this.sn = sn == null ? null : sn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rechargecard_info.pw
     *
     * @return the value of tb_rechargecard_info.pw
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    public String getPw() {
        return pw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rechargecard_info.pw
     *
     * @param pw the value for tb_rechargecard_info.pw
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    public void setPw(String pw) {
        this.pw = pw == null ? null : pw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rechargecard_info.used
     *
     * @return the value of tb_rechargecard_info.used
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    public Integer getUsed() {
        return used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rechargecard_info.used
     *
     * @param used the value for tb_rechargecard_info.used
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    public void setUsed(Integer used) {
        this.used = used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rechargecard_info.sku
     *
     * @return the value of tb_rechargecard_info.sku
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    public Long getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rechargecard_info.sku
     *
     * @param sku the value for tb_rechargecard_info.sku
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    public void setSku(Long sku) {
        this.sku = sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rechargecard_info.price
     *
     * @return the value of tb_rechargecard_info.price
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rechargecard_info.price
     *
     * @param price the value for tb_rechargecard_info.price
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rechargecard_info.currency
     *
     * @return the value of tb_rechargecard_info.currency
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rechargecard_info.currency
     *
     * @param currency the value for tb_rechargecard_info.currency
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rechargecard_info.used_time
     *
     * @return the value of tb_rechargecard_info.used_time
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    public Date getUsedTime() {
        return usedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rechargecard_info.used_time
     *
     * @param usedTime the value for tb_rechargecard_info.used_time
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    public void setUsedTime(Date usedTime) {
        this.usedTime = usedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rechargecard_info.created_by
     *
     * @return the value of tb_rechargecard_info.created_by
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rechargecard_info.created_by
     *
     * @param createdBy the value for tb_rechargecard_info.created_by
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rechargecard_info.expired_time
     *
     * @return the value of tb_rechargecard_info.expired_time
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    public Date getExpiredTime() {
        return expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rechargecard_info.expired_time
     *
     * @param expiredTime the value for tb_rechargecard_info.expired_time
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    public void setExpiredTime(Date expiredTime) {
        this.expiredTime = expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rechargecard_info.created_time
     *
     * @return the value of tb_rechargecard_info.created_time
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rechargecard_info.created_time
     *
     * @param createdTime the value for tb_rechargecard_info.created_time
     *
     * @mbggenerated Thu Apr 14 12:13:54 CST 2016
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
}